# Generated by Django 3.1.3 on 2020-11-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=200)),
                ('email', models.EmailField(editable=False, max_length=200)),
                ('content', models.TextField(editable=False)),
                ('contact_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
